Repository 242darkman/DynamicQuizChallenge, pull requests merged in 2024-02, with the labels that each got.

#2 Fix/bug correction
  packages/core-dynamic-quizz/src/quiz/gateway/quiz.gateway.ts
  packages/core-dynamic-quizz/src/quiz/service/room/room.service.ts
Labels: bug

#3 Fix/bug correction
  packages/core-dynamic-quizz/src/quiz/gateway/quiz.gateway.ts
  packages/office-dynamic-quizz/package.json
  packages/office-dynamic-quizz/src/app/room/page.js
  packages/office-dynamic-quizz/src/app/room/settings/page.js
  packages/office-dynamic-quizz/src/app/room/waiting-room/page.js
Labels: bug

#6 Feat/ci cd workflows
  packages/core-dynamic-quizz/.env
  packages/core-dynamic-quizz/src/quiz/model/connected-user/connected-user.entity.ts
  packages/core-dynamic-quizz/src/quiz/model/connected-user/connected-user.interface.ts
  packages/core-dynamic-quizz/src/quiz/model/joined-room/joined-room.entity.ts
  packages/core-dynamic-quizz/src/quiz/model/joined-room/joined-room.interface.ts
  packages/core-dynamic-quizz/src/quiz/model/question/question.entity.ts
  packages/core-dynamic-quizz/src/quiz/model/quiz/quiz.entity.ts
  packages/core-dynamic-quizz/src/quiz/model/quiz/quiz.interface.ts
  packages/core-dynamic-quizz/src/quiz/model/room/room.entity.ts
  packages/core-dynamic-quizz/src/quiz/model/room/room.interface.ts
  packages/core-dynamic-quizz/src/quiz/model/subject/subject.entity.ts
  packages/core-dynamic-quizz/src/quiz/model/subject/subject.interface.ts
  packages/core-dynamic-quizz/src/quiz/quiz.module.ts
  packages/core-dynamic-quizz/src/quiz/service/openai/openai.service.ts
  packages/core-dynamic-quizz/src/quiz/service/quiz/quiz.service.ts
  packages/core-dynamic-quizz/src/quiz/service/room/room.service.ts
  packages/core-dynamic-quizz/src/quiz/service/subject/subject.service.spec.ts
  packages/core-dynamic-quizz/src/quiz/service/subject/subject.service.ts
Labels: fix code

#7 Feat/add room params
  .github/workflows/hadolint.yml
  packages/core-dynamic-quizz/src/middleware/auth/auth.middleware.ts
  packages/core-dynamic-quizz/src/quiz/gateway/quiz.gateway.ts
  packages/core-dynamic-quizz/src/quiz/model/room/room.entity.ts
  packages/core-dynamic-quizz/src/quiz/model/room/setting/room-setting.entity.ts
  packages/core-dynamic-quizz/src/quiz/model/room/setting/room-setting.interface.ts
  packages/core-dynamic-quizz/src/quiz/quiz.module.ts
  packages/core-dynamic-quizz/src/quiz/service/room-setting/room-setting.service.spec.ts
  packages/core-dynamic-quizz/src/quiz/service/room-setting/room-setting.service.ts
  packages/core-dynamic-quizz/src/quiz/service/room/room.service.ts
  packages/core-dynamic-quizz/src/user/model/user.entity.ts
  packages/core-dynamic-quizz/src/user/model/user.interface.ts
  packages/core-dynamic-quizz/src/user/service/user-service/user.service.ts
  packages/office-dynamic-quizz/src/app/_constants/settingsOptions.js
  packages/office-dynamic-quizz/src/app/_context/AuthContext.js
  packages/office-dynamic-quizz/src/app/_context/AuthProvider.js
  packages/office-dynamic-quizz/src/app/_context/RoomContext.js
  packages/office-dynamic-quizz/src/app/_context/SocketContext.js
  packages/office-dynamic-quizz/src/app/auth/signin/page.js
  packages/office-dynamic-quizz/src/app/layout.js
  packages/office-dynamic-quizz/src/app/page.js
  packages/office-dynamic-quizz/src/app/room/page.js
  packages/office-dynamic-quizz/src/app/room/question/page.js
  packages/office-dynamic-quizz/src/app/room/ranking/page.js
  packages/office-dynamic-quizz/src/app/room/settings/page.js
  packages/office-dynamic-quizz/src/app/room/waiting-room/page.js
Labels: feature

#10 Feat/ci cd workflows : add CI/CD workflows and release drafter
  .github/release-drafter.yml
  .github/workflows/ci_cd.yml
  packages/office-dynamic-quizz/.eslintrc.json
  packages/office-dynamic-quizz/.prettierrc
  packages/office-dynamic-quizz/.vscode/settings.json
  packages/office-dynamic-quizz/package.json
Labels: feature

#11 Feat/generation of questions by theme with openapi
  packages/core-dynamic-quizz/.env
  packages/core-dynamic-quizz/src/main.ts
  packages/core-dynamic-quizz/src/quiz/gateway/quiz.gateway.ts
  packages/core-dynamic-quizz/src/quiz/quiz.module.ts
  packages/core-dynamic-quizz/src/quiz/service/openai/openai.service.ts
  packages/office-dynamic-quizz/src/app/_context/RoomContext.js
  packages/office-dynamic-quizz/src/app/_utils/game.js
  packages/office-dynamic-quizz/src/app/room/page.js
  packages/office-dynamic-quizz/src/app/room/question/page.js
  packages/office-dynamic-quizz/src/app/room/ranking/page.js
  packages/office-dynamic-quizz/src/app/room/settings/page.js
  packages/office-dynamic-quizz/src/app/room/waiting-room/page.js
Labels: feature

#12 Feat/UI improvements and generations of contextual explanatory hints
  packages/core-dynamic-quizz/src/quiz/gateway/quiz.gateway.ts
  packages/core-dynamic-quizz/src/quiz/quiz.module.ts
  packages/core-dynamic-quizz/src/quiz/service/openai/openai.service.ts
  packages/office-dynamic-quizz/src/app/_components/QuestionDisplay.jsx
  packages/office-dynamic-quizz/src/app/_components/ui/FooterUI.jsx
  packages/office-dynamic-quizz/src/app/_components/ui/HeaderUI.jsx
  packages/office-dynamic-quizz/src/app/_constants/settingsOptions.js
  packages/office-dynamic-quizz/src/app/_constants/translationMap.js
  packages/office-dynamic-quizz/src/app/_context/AuthContext.js
  packages/office-dynamic-quizz/src/app/_utils/game.js
  packages/office-dynamic-quizz/src/app/room/question/page.js
Labels: feature

#13 fix: correction unit test
  packages/core-dynamic-quizz/package.json
  packages/core-dynamic-quizz/src/app.controller.spec.ts
  packages/core-dynamic-quizz/src/auth/service/auth.service.spec.ts
  packages/core-dynamic-quizz/src/quiz/gateway/quiz.gateway.spec.ts
  packages/core-dynamic-quizz/src/quiz/service/connected-user/connected-user.service.spec.ts
  packages/core-dynamic-quizz/src/quiz/service/joined-room/joined-room.service.spec.ts
  packages/core-dynamic-quizz/src/quiz/service/quiz/quiz.service.spec.ts
  packages/core-dynamic-quizz/src/quiz/service/room-setting/room-setting.service.spec.ts
  packages/core-dynamic-quizz/src/quiz/service/room/room.service.spec.ts
  packages/core-dynamic-quizz/src/user/controller/user.controller.spec.ts
  packages/core-dynamic-quizz/src/user/service/user-service/user.service.spec.ts
Labels: fix code

#15 Feat/UI improvements and generations of contextual explanatory hints
  README.md
  docker-compose.yml
  packages/core-dynamic-quizz/Dockerfile
  packages/office-dynamic-quizz/Dockerfile
Labels: fix code

#16 fix:clean code et correction des bugs
  packages/office-dynamic-quizz/.eslintignore
  packages/office-dynamic-quizz/src/app/_components/ui/HeaderUI.jsx
  packages/office-dynamic-quizz/src/app/_context/SocketContext.js
  packages/office-dynamic-quizz/src/app/room/page.js
  packages/office-dynamic-quizz/src/app/room/question/page.js
  packages/office-dynamic-quizz/src/app/room/settings/page.js
  packages/office-dynamic-quizz/src/app/room/waiting-room/page.js
Labels: fix code

#17 Suite clean
  .DS_Store
  packages/.DS_Store
  packages/core-dynamic-quizz/.env
  packages/core-dynamic-quizz/src/quiz/gateway/quiz.gateway.ts
  packages/core-dynamic-quizz/src/quiz/model/question/question.entity.ts
  packages/core-dynamic-quizz/src/quiz/model/question/question.interface.ts
  packages/core-dynamic-quizz/src/quiz/model/quiz/quiz.entity.ts
  packages/core-dynamic-quizz/src/quiz/model/quiz/quiz.interface.ts
  packages/core-dynamic-quizz/src/quiz/model/ranking/ranking.interface.ts
  packages/core-dynamic-quizz/src/quiz/model/ranking/ranking.ts
  packages/core-dynamic-quizz/src/quiz/model/room/room.entity.ts
  packages/core-dynamic-quizz/src/quiz/quiz.module.ts
  packages/core-dynamic-quizz/src/quiz/service/joined-room/joined-room.service.ts
  packages/core-dynamic-quizz/src/quiz/service/question/question.service.spec.ts
  packages/core-dynamic-quizz/src/quiz/service/question/question.service.ts
  packages/core-dynamic-quizz/src/quiz/service/quiz/quiz.service.ts
Labels: fix code
